package com.haven.simplej.security.enums;

/**
 * Created by haven.zhang on 2019/1/3.
 */
public enum PEBAlgorithms {


	PBEWithSHAAndDES("PBEWithSHAAndDES"),
	PBEWithHmacSHA256AndAES_128("PBEWithHmacSHA256AndAES_128"),
	PBEWithMD5AndTripeDES("PBEWithMD5AndTripeDES"),
	PBEWithSHA1AndDESede("PBEWithSHA1AndDESede"),
	PBEWithSHA1AndIDEA_CBC("PBEWithSHA1AndIDEA-CBC"),
	PBEWITHSHAANDRC2("PBEWITHSHAANDRC2"),
	PBEWITHSHAANDRC4("PBEWITHSHAANDRC4"),
	PBEWITHMD2ANDDES("PBEWITHMD2ANDDES"),

	PBEWithSHAAndTwofish_CBC("PBEWithSHAAndTwofish-CBC"),
	PBEWithSHAAnd40BitRC4("PBEWithSHAAnd40BitRC4"),
	PBEWithSHAAnd128BitRC4("PBEWithSHAAnd128BitRC4"),
	PBEWithSHAAnd40BitRC2_CBC("PBEWithSHAAnd40BitRC2-CBC"),
	PBEWithSHAAnd128BitRC2_CBC("PBEWithSHAAnd128BitRC2-CBC"),
	PBEWithSHAAnd3_KeyTripleDES_CBC ("PBEWithSHAAnd3-KeyTripleDES-CBC"),
	PBEWithSHAAnd2_KeyTripleDES_CBC("PBEWithSHAAnd2-KeyTripleDES-CBC"),
	PBEWithSHA1AndRC2("PBEWithSHA1AndRC2"),
	PBEWithMD5AndDES("PBEWithMD5AndDES"),
	PBEWithSHA1AndDES("PBEWithSHA1AndDES"),
	PBEWITHSHA256AND256BITAES_CBC_BC("PBEWITHSHA256AND256BITAES-CBC-BC"),
	PBEWITHSHA256AND192BITAES_CBC_BC("PBEWITHSHA256AND192BITAES-CBC-BC"),
	PBEWITHSHA256AND128BITAES_CBC_BC("PBEWITHSHA256AND128BITAES-CBC-BC"),
	PBEWITHSHAAND256BITAES_CBC_BC("PBEWITHSHAAND256BITAES-CBC-BC"),
	PBEWITHSHAAND192BITAES_CBC_BC("PBEWITHSHAAND192BITAES-CBC-BC"),
	PBEWITHSHAAND128BITAES_CBC_BC("PBEWITHSHAAND128BITAES-CBC-BC"),
	PBEWithMD5AndRC2("PBEWithMD5AndRC2");

	private String value;

	PEBAlgorithms(String value){
		this.value = value;
	}

	public String getValue() {
		return value;
	}

}